version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/app:cached
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  db:
    image: mariadb
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"

  redis:
    image: redis

  rabbitmq:
    build: ./rabbit
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
      RABBITMQ_DEFAULT_VHOST: /
